language: csharp
mono: none
dotnet: 2.1
solution: Cactus.Fileserver.sln
script:
  - dotnet restore
  - dotnet build
  - dotnet test Cactus.Fileserver.Tests/Cactus.Fileserver.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover